version: '3'

services:
    brevets:
        build: brevets/.
        command: flask_brevets.py
        ports: 
          - "5000:5000"
        environment:
          MONGODB_HOSTNAME: brevetsdb
    brevetsdb:
      image: mongo:5.0.5